### ISSUE TITLE
How to update the PYTHON path for TensorRT 5.0 install?

### ISSUE THREAD

**Issue by bfortuner** [onnx/onnx-tensorrt#115]
"If you are using TRT 5.0 libraries you need these updated bindings to create a parser object in python."

Hey sorry if I'm ignorant, but how do I do this exactly? I'm using the Nvidia TensorRT 5.0 docker container. I have everything running there except the onnx-tensorrt python wrapper. Right now I'm getting "module not found" when I import outside the onnx-tensorrt repo

Here's your snippet from the wiki:

"TensorRT version 5.0 and up create Python wrappers using pybind11. No build is necessary. However, since we use already existing TensorRT binding, we need to ensure that PYTHONPATH is set appropriately. If you just install TensorRT, the weels for the pybind will be located at the same location other TensorRT libs."

When I try to import onnx_tensorrt.backend from inside the onnx-tensorrt repo I get:

>>> import onnx_tensorrt.backend as backend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/onnx-tensorrt/onnx_tensorrt/__init__.py", line 23, in <module>
    from . import backend
  File "/workspace/onnx-tensorrt/onnx_tensorrt/backend.py", line 22, in <module>
    from .tensorrt_engine import Engine
  File "/workspace/onnx-tensorrt/onnx_tensorrt/tensorrt_engine.py", line 22, in <module>
    import pycuda.driver
  File "/usr/local/lib/python3.5/dist-packages/pycuda/driver.py", line 5, in <module>
    from pycuda._driver import *  # noqa
ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short

Do i need to manually install pycuda?

**Comment by kevinch-nv** [comment]
Hi @bfortuner, are you able to reproduce this with the latest TensorRT release? We have made many more updates since TRT 5.0.

**Comment by kevinch-nv** [comment]
Closing due to inactivity - if you are still having issues with the latest version of onnx-tensorrt feel free to open a new issue.
