### ISSUE TITLE
onnx-tensorrt(tensorrt6) read yolov3.onnx is error

### ISSUE THREAD

**Issue by 17702513221** [onnx/onnx-tensorrt#258]
I use onnx-tensorrt(tensorrt6) read yolov3.onnx(https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3)  is error:
[TensorRT] ERROR: Parameter check failed at: ../builder/Network.cpp::addInput::671, condition: isValidDims(dims, hasImplicitBatchDimension())
untimeError: While parsing node number -1:
ModelImporter.cpp:80 In function importInput:
[8] Assertion failed: *tensor = importer_ctx->network()->addInput( input.name().c_str(), trt_dtype, trt_dims)
model = onnx.load("yolov3.onnx")
engine = backend.prepare(model, device='CUDA:0')

**Comment by jgabriellima** [comment]
I'm facing the same issue @here:
`>>> engine = backend.prepare(model)
[TensorRT] ERROR: Parameter check failed at: ../builder/Network.cpp::addInput::465, condition: isValidDims(dims)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dp/onnx-tensorrt/onnx_tensorrt/backend.py", line 218, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/home/dp/onnx-tensorrt/onnx_tensorrt/backend.py", line 94, in __init__
    raise RuntimeError(msg)
RuntimeError: While parsing node number -1:
ModelImporter.cpp:80 In function importInput:
[8] Assertion failed: *tensor = importer_ctx->network()->addInput( input.name().c_str(), trt_dtype, trt_dims)`

**Comment by Rapternmn** [comment]
Try this implementation
https://github.com/Rapternmn/PyTorch-Onnx-Tensorrt

**Comment by kevinch-nv** [comment]
Can you try running the model with the latest TensorRT version to see if you are still having the same issue?

**Comment by kevinch-nv** [comment]
Closing due to inactivity - if you are still having issues feel free to reopen.
