### ISSUE TITLE
When import a onnx file contains unsqueeze op of a tensor, failed. TensorRT6.0

### ISSUE THREAD

**Issue by apache2046** [onnx/onnx-tensorrt#279]
```
#0  0x00007fffeade7883 in nvinfer1::ShuffleLayer::getOutputDimensions(nvinfer1::Dims const&) const () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.6
#1  0x00007fffeade84f1 in nvinfer1::ShuffleLayer::validate(std::vector<nvinfer1::TensorForm, std::allocator<nvinfer1::TensorForm> > const&, nvinfer1::NetworkLayer::ValidationContext const&) const ()
   from /usr/lib/x86_64-linux-gnu/libnvinfer.so.6
#2  0x00007fffead83933 in nvinfer1::Network::updateTensor(nvinfer1::NetworkTensor const*) const () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.6
#3  0x00007fffead83cda in nvinfer1::NetworkTensor::getDimensions() const () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.6
#4  0x00007fffea334850 in ?? () from /usr/lib/x86_64-linux-gnu/libnvonnxparser.so.6
#5  0x00007fffea336949 in ?? () from /usr/lib/x86_64-linux-gnu/libnvonnxparser.so.6
#6  0x00007fffea2ffe0a in ?? () from /usr/lib/x86_64-linux-gnu/libnvonnxparser.so.6
#7  0x00007fffea302bc3 in ?? () from /usr/lib/x86_64-linux-gnu/libnvonnxparser.so.6
#8  0x00007fffea305210 in ?? () from /usr/lib/x86_64-linux-gnu/libnvonnxparser.so.6
#9  0x00007fffea306bbc in ?? () from /usr/lib/x86_64-linux-gnu/libnvonnxparser.so.6
#10 0x000055555557300e in sample::modelToNetwork(sample::ModelOptions const&, nvinfer1::INetworkDefinition&, std::ostream&) ()
#11 0x00005555555752d3 in sample::modelToEngine(sample::ModelOptions const&, sample::BuildOptions const&, sample::SystemOptions const&, std::ostream&) ()
#12 0x00005555555596fa in main ()

```

**Comment by kevinch-nv** [comment]
Closing this issue as the MR has been merged.
