### ISSUE TITLE
ImportError: No module named 'onnx_tensorrt.parser._nv_onnx_parser_bindings'

### ISSUE THREAD

**Issue by anish9** [onnx/onnx-tensorrt#29]
After running all the installation instruction provided, onnx-tensorrt was successfully installed with python==3.5, cuda==9.2, cudnn==7.2, nvcc==9.2.

But while performing the command to test the library, the test program is returning this error:
```

Traceback (most recent call last):
  File "onnx_backend_test.py", line 31, in <module>
    import onnx_tensorrt.backend as trt
  File "/home/anish-fujitsu/onnx-tensorrt/onnx_tensorrt/__init__.py", line 23, in <module>
    from . import backend
  File "/home/anish-fujitsu/onnx-tensorrt/onnx_tensorrt/backend.py", line 22, in <module>
    from . import parser
  File "/home/anish-fujitsu/onnx-tensorrt/onnx_tensorrt/parser/__init__.py", line 23, in <module>
    from ._nv_onnx_parser_bindings import *
ImportError: No module named 'onnx_tensorrt.parser._nv_onnx_parser_bindings'

```
Any help, appreciated.

**Comment by ChengshuLi** [comment]
@anish9 

I received the same error. How did you solve this problem? Thanks!

**Comment by anish9** [comment]
@ChengshuLi  
in my case the location paths were incorrect just rectify the right path with right file present and that will fix the issue.

**Comment by myih** [comment]
@anish9 Hi
What's the proper way to rectify the path? 
I use  import sys and sys.path.append('/usr/local/lib/python3.5/dist-packages/onnx_tensorrt-0.1.0-py3.5-linux-x86_64.egg/onnx_tensorrt/parser/'),
but now I have a new error 
```
File "onnx_backend_test.py", line 31, in <module>  import onnx_tensorrt.backend as trt
  File "/home/onnx-tensorrt/onnx_tensorrt/__init__.py", line 23, in <module>  from . import backend
  File "/home/onnx-tensorrt/onnx_tensorrt/backend.py", line 22, in <module>   from . import parser
  File "/home/onnx-tensorrt/onnx_tensorrt/parser/__init__.py", line 24, in <module>  from _nv_onnx_parser_bindings import *
ImportError: libnvonnxparser.so.0: cannot open shared object file: No such file or directory
```

Thank you!

**Comment by bpinaya** [comment]
I also encounter the same error and can't get past it, I tried with conda and without it, and that `ImportError: No module named _nv_onnx_parser_bindings`. I'm on TensorRT 5.0.2GA.
Anyone had any luck?

**Comment by youwei11** [comment]
mkdir build && \
    cd build && \
    cmake .. && \
    make -j$(nproc) && \
    make install && \
    **ldconfig**

try  ldconfig

**Comment by bpinaya** [comment]
@youwei11 I tried ldconfig and didn't work, did you get it to work on TensorRT5.0.2GA? I used TRT4 and there it works correctly.

**Comment by endeavor11** [comment]
> mkdir build &&
> cd build &&
> cmake .. &&
> make -j$(nproc) &&
> make install &&
> **ldconfig**
> 
> try ldconfig

Could you tell me where I should create the build folder？
Thanks！
