### ISSUE TITLE
 An error occurred during inference

### ISSUE THREAD

**Issue by zhoulukuan** [onnx/onnx-tensorrt#329]
Hi, I am having trouble using the Onnx model for inference.
Code:
```
import onnx_tensorrt.backend as backend
import cv2
import onnx
import numpy as np

model = onnx.load("/home/zlk/mmdetection/test.onnx")
engine = backend.prepare(model, device='CUDA:0')
path = '/home/zlk/mmdetection/onnx/test.jpg'
img = cv2.imread(path)
print(img.shape)
img = cv2.resize(img,(800,800))
img = img.transpose(2,0,1)
img = np.ascontiguousarray(img)
img = img[np.newaxis,:]
print(img.shape)
input_data= img.astype(np.float32)
output_data = engine.run(input_data)
print(output_data)
```
Error info:
```
Traceback (most recent call last):
  File "check.py", line 7, in <module>
    engine = backend.prepare(model, device='CUDA:0')
  File "/home/zlk/onnx-tensorrt/onnx_tensorrt/backend.py", line 217, in prepare
    super(TensorRTBackend, cls).prepare(model, device, **kwargs)
  File "/home/zlk/anaconda3/envs/mm/lib/python3.6/site-packages/onnx/backend/base.py", line 74, in prepare
    onnx.checker.check_model(model)
  File "/home/zlk/anaconda3/envs/mm/lib/python3.6/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 1 not in range [min=3, max=5].

==> Context: Bad node spec: input: "562" output: "563" op_type: "Slice" attribute { name: "axes" ints: 0 type: INTS } attribute { name: "ends" ints: 4 type: INTS } attribute { name: "starts" ints: 2 type: INTS }
```
I train model with [mmdetection](https://github.com/open-mmlab/mmdetection) and have converted original model to onnx model successfully. The nodes near 562 are shown as follwo:
```
  %540 : Float(1, 2048, 25, 25) = onnx::Add(%539, %531), scope: FCOS/ResNet[backbone]/Sequential[layer4]/Bottleneck[2]
  %541 : Float(1, 2048, 25, 25) = onnx::Relu(%540), scope: FCOS/ResNet[backbone]/Sequential[layer4]/Bottleneck[2]/ReLU[relu]
  %542 : Float(1, 256, 100, 100) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%447, %neck.lateral_convs.0.conv.weight, %neck.lateral_convs.0.conv.bias), scope: FCOS/FPN[neck]/ConvModule/Conv2d[conv]
  %543 : Float(1, 256, 50, 50) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%509, %neck.lateral_convs.1.conv.weight, %neck.lateral_convs.1.conv.bias), scope: FCOS/FPN[neck]/ConvModule/Conv2d[conv]
  %544 : Float(1, 256, 25, 25) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%541, %neck.lateral_convs.2.conv.weight, %neck.lateral_convs.2.conv.bias), scope: FCOS/FPN[neck]/ConvModule/Conv2d[conv]
  %545 : Long() = onnx::Constant[value={2}](), scope: FCOS/FPN[neck]
  %546 : Tensor = onnx::Shape(%544), scope: FCOS/FPN[neck]
  %547 : Long() = onnx::Gather[axis=0](%546, %545), scope: FCOS/FPN[neck]
  %548 : Tensor = onnx::Constant[value={2}]()
  %549 : Tensor = onnx::Mul(%547, %548)
  %550 : Float() = onnx::Floor(%549), scope: FCOS/FPN[neck]
  %551 : Long() = onnx::Constant[value={3}](), scope: FCOS/FPN[neck]
  %552 : Tensor = onnx::Shape(%544), scope: FCOS/FPN[neck]
  %553 : Long() = onnx::Gather[axis=0](%552, %551), scope: FCOS/FPN[neck]
  %554 : Tensor = onnx::Constant[value={2}]()
  %555 : Tensor = onnx::Mul(%553, %554)
  %556 : Float() = onnx::Floor(%555), scope: FCOS/FPN[neck]
  %557 : Tensor = onnx::Unsqueeze[axes=[0]](%550)
  %558 : Tensor = onnx::Unsqueeze[axes=[0]](%556)
  %559 : Tensor = onnx::Concat[axis=0](%557, %558)
  %560 : Tensor = onnx::Constant[value= 1  1 [ Variable[CPUType]{2} ]](), scope: FCOS/FPN[neck]
  %561 : Tensor = onnx::Cast[to=1](%559), scope: FCOS/FPN[neck]
  %562 : Tensor = onnx::Shape(%544), scope: FCOS/FPN[neck]
  %563 : Tensor = onnx::Slice[axes=[0], ends=[4], starts=[2]](%562), scope: FCOS/FPN[neck]
  %564 : Tensor = onnx::Cast[to=1](%563), scope: FCOS/FPN[neck]
  %565 : Tensor = onnx::Div(%561, %564), scope: FCOS/FPN[neck]
  %566 : Tensor = onnx::Concat[axis=0](%560, %565), scope: FCOS/FPN[neck]
  %567 : Float(1, 256, 50, 50) = onnx::Upsample[mode="nearest"](%544, %566), scope: FCOS/FPN[neck]
  %568 : Float(1, 256, 50, 50) = onnx::Add(%543, %567), scope: FCOS/FPN[neck]
  %569 : Long() = onnx::Constant[value={2}](), scope: FCOS/FPN[neck]
  %570 : Tensor = onnx::Shape(%568), scope: FCOS/FPN[neck]
  %571 : Long() = onnx::Gather[axis=0](%570, %569), scope: FCOS/FPN[neck]
  %572 : Tensor = onnx::Constant[value={2}]()
  %573 : Tensor = onnx::Mul(%571, %572)
  %574 : Float() = onnx::Floor(%573), scope: FCOS/FPN[neck]
  %575 : Long() = onnx::Constant[value={3}](), scope: FCOS/FPN[neck]
  %576 : Tensor = onnx::Shape(%568), scope: FCOS/FPN[neck]
  %577 : Long() = onnx::Gather[axis=0](%576, %575), scope: FCOS/FPN[neck]
  %578 : Tensor = onnx::Constant[value={2}]()
  %579 : Tensor = onnx::Mul(%577, %578)
  %580 : Float() = onnx::Floor(%579), scope: FCOS/FPN[neck]
  %581 : Tensor = onnx::Unsqueeze[axes=[0]](%574)
  %582 : Tensor = onnx::Unsqueeze[axes=[0]](%580)
  %583 : Tensor = onnx::Concat[axis=0](%581, %582)
  %584 : Tensor = onnx::Constant[value= 1  1 [ Variable[CPUType]{2} ]](), scope: FCOS/FPN[neck]
  %585 : Tensor = onnx::Cast[to=1](%583), scope: FCOS/FPN[neck]
  %586 : Tensor = onnx::Shape(%568), scope: FCOS/FPN[neck]
  %587 : Tensor = onnx::Slice[axes=[0], ends=[4], starts=[2]](%586), scope: FCOS/FPN[neck]
  %588 : Tensor = onnx::Cast[to=1](%587), scope: FCOS/FPN[neck]
  %589 : Tensor = onnx::Div(%585, %588), scope: FCOS/FPN[neck]
  %590 : Tensor = onnx::Concat[axis=0](%584, %589), scope: FCOS/FPN[neck]
  %591 : Float(1, 256, 100, 100) = onnx::Upsample[mode="nearest"](%568, %590), scope: FCOS/FPN[neck]
  %592 : Float(1, 256, 100, 100) = onnx::Add(%542, %591), scope: FCOS/FPN[neck]
```
It seems that some operator in [mmdetection FPN part](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/necks/fpn.py) have some problems. But I think that fpn only used common opearator such as conv or upsample. So why I met this problem and how to solve it?

**Comment by jinfagang** [comment]
Possible miss version of op Slice,

from opset11, Slice needs at least 3 input which are: data, starts, ends, you possiblely export your onnx model in Slice-1. You should check your opset version to fix it.

**Comment by zhoulukuan** [comment]
@jinfagang Before, I use opset10:
```
torch.onnx.export(model, dummy_input, "test.onnx", verbose=True, opset_version=10)
```
If I set opset_version=11, it will raise ValueError `Unsupported ONNX opset version: 11`. Could you tell me how to use opset11?

**Comment by jinfagang** [comment]
pytorch 1.3 introduced new support of opset 11

**Comment by kevinch-nv** [comment]
@zhoulukuan are you still having issues with your model? Are you able to reproduce on the latest TRT version?

**Comment by zhoulukuan** [comment]
> @zhoulukuan are you still having issues with your model? Are you able to reproduce on the latest TRT version?

Yes. I can reproduce with opset 11. However, I adjusted the model later and did not use special operations such as GN. I am not sure if this has any effect.
