### ISSUE TITLE
Error of onnx_tensorrt package of python when runing

### ISSUE THREAD

**Issue by verigle** [onnx/onnx-tensorrt#342]
sometime the error like this:

> Traceback (most recent call last):
>   File "/media/verigle/1CBEE09ABEE06E28/projects/Face/RetinaFace/detect_face_tensorrt.py", line 12, in <module>
>     import onnx_tensorrt.backend as backend
>   File "/home/verigle/miniconda3/envs/pytorch/lib/python3.7/site-packages/onnx_tensorrt-0.1.0-py3.7-linux-x86_64.egg/onnx_tensorrt/__init__.py", line 23, in <module>
>     from . import backend
>   File "/home/verigle/miniconda3/envs/pytorch/lib/python3.7/site-packages/onnx_tensorrt-0.1.0-py3.7-linux-x86_64.egg/onnx_tensorrt/backend.py", line 22, in <module>
>     from .tensorrt_engine import Engine
>   File "/home/verigle/miniconda3/envs/pytorch/lib/python3.7/site-packages/onnx_tensorrt-0.1.0-py3.7-linux-x86_64.egg/onnx_tensorrt/tensorrt_engine.py", line 24, in <module>
>     import pycuda.autoinit
>   File "/home/verigle/miniconda3/envs/pytorch/lib/python3.7/site-packages/pycuda/autoinit.py", line 9, in <module>
>     context = make_default_context()
>   File "/home/verigle/miniconda3/envs/pytorch/lib/python3.7/site-packages/pycuda/tools.py", line 204, in make_default_context
>     "on any of the %d detected devices" % ndevices)
> RuntimeError: make_default_context() wasn't able to create a context on any of the 1 detected devices

but sometimes the error like this:

> 
> Traceback (most recent call last):
>   File "/media/verigle/1CBEE09ABEE06E28/projects/Face/RetinaFace/detect_face_tensorrt.py", line 100, in <module>
>     engine = backend.prepare(model, device='CUDA')
>   File "/home/verigle/miniconda3/envs/pytorch/lib/python3.7/site-packages/onnx_tensorrt-0.1.0-py3.7-linux-x86_64.egg/onnx_tensorrt/backend.py", line 200, in prepare
>     return TensorRTBackendRep(model, device, **kwargs)
>   File "/home/verigle/miniconda3/envs/pytorch/lib/python3.7/site-packages/onnx_tensorrt-0.1.0-py3.7-linux-x86_64.egg/onnx_tensorrt/backend.py", line 86, in __init__
>     raise RuntimeError(msg)
> RuntimeError: While parsing node number 92:
> /home/verigle/Projects/Github/onnx-tensorrt/builtin_op_importers.cpp:703 In function importGather:
> [8] Assertion failed: !(data->getType() == nvinfer1::DataType::kINT32 && nbDims == 1) && "Cannot perform gather on a shape tensor!"

**Comment by kevinch-nv** [comment]
Hi @verigle we've made some updates to the onnx-tensorrt backend over the past few TRT releases. Are you able the reproduce this with the latest version of onnx-tensorrt?

**Comment by kevinch-nv** [comment]
Closing due to inactivity - please upgrade to the latest TRT version and try importing your model again. If that doesn't work, feel free to open a new issue.
