### ISSUE TITLE
Docker test fails

### ISSUE THREAD

**Issue by granjanrak1** [onnx/onnx-tensorrt#37]
docker test fails for command
```
python onnx_backend_test.py OnnxBackendRealModelTest
```
Output :
```
======================================================================
ERROR: test_densenet121_cuda (__main__.OnnxBackendRealModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/onnx-1.1.1-py2.7-linux-x86_64.egg/onnx/backend/test/runner/__init__.py", line 211, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/onnx-1.1.1-py2.7-linux-x86_64.egg/onnx/backend/test/runner/__init__.py", line 237, in run
    prepared_model = self.backend.prepare(model, device)
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 178, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 74, in __init__
    raise RuntimeError(msg)
RuntimeError: While parsing node number 2:
/opt/onnx2trt/ModelImporter.cpp:141 In function importNode:
[8] No importer registered for op: Unsqueeze

======================================================================
ERROR: test_inception_v2_cuda (__main__.OnnxBackendRealModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/onnx-1.1.1-py2.7-linux-x86_64.egg/onnx/backend/test/runner/__init__.py", line 211, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/onnx-1.1.1-py2.7-linux-x86_64.egg/onnx/backend/test/runner/__init__.py", line 237, in run
    prepared_model = self.backend.prepare(model, device)
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 178, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 74, in __init__
    raise RuntimeError(msg)
RuntimeError: While parsing node number 2:
/opt/onnx2trt/ModelImporter.cpp:141 In function importNode:
[8] No importer registered for op: Unsqueeze

======================================================================
ERROR: test_shufflenet_cuda (__main__.OnnxBackendRealModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/onnx-1.1.1-py2.7-linux-x86_64.egg/onnx/backend/test/runner/__init__.py", line 211, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/onnx-1.1.1-py2.7-linux-x86_64.egg/onnx/backend/test/runner/__init__.py", line 237, in run
    prepared_model = self.backend.prepare(model, device)
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 178, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 74, in __init__
    raise RuntimeError(msg)
RuntimeError: While parsing node number 7:
/opt/onnx2trt/builtin_op_importers.cpp:1323 In function importReshape:
[8] Assertion failed: new_shape.nbDims == 3

----------------------------------------------------------------------
Ran 18 tests in 141.325s

FAILED (errors=3, skipped=9)
```

**Comment by yinghai** [comment]
Dup of https://github.com/onnx/onnx-tensorrt/issues/38?
