### ISSUE TITLE
TypeError: must be str, not bytes

### ISSUE THREAD

**Issue by cloudrivers** [onnx/onnx-tensorrt#379]
Hi 
  
  When i follow sample code to inference with a pytorch model. below code will throw an error 'TypeError: must be str, not bytes'.
  engine = backend.prepare(model, device= "CUDA:1") 

Traceback (most recent call last):
  File "helloworld.py", line 9, in <module>
    engine = backend.prepare(model, device= "CUDA:1")
  File "/usr/local/lib/python3.6/dist-packages/onnx_tensorrt/backend.py", line 218, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/onnx_tensorrt/backend.py", line 68, in __init__
    self._set_device(device)
  File "/usr/local/lib/python3.6/dist-packages/onnx_tensorrt/backend.py", line 124, in _set_device
    cudaSetDevice(device.device_id)
  File "/usr/local/lib/python3.6/dist-packages/onnx_tensorrt/backend.py", line 39, in cudaSetDevice
    raise RuntimeError("cudaSetDevice: " + error_string)
TypeError: must be str, not bytes

**Comment by riyadshairi979** [comment]
Same problem with me, any workaround?

**Comment by riyadshairi979** [comment]
The actual error is not reported. With the below code I found actual error happening here:
```from ctypes import cdll, c_char_p
libcudart = cdll.LoadLibrary('libcudart.so')
libcudart.cudaGetErrorString.restype = c_char_p
ret = libcudart.cudaSetDevice(1)
print(libcudart.cudaGetErrorString(ret))```
And that is-
```CUDA driver version is insufficient for CUDA runtime version```

**Comment by kevinch-nv** [comment]
@cloudrivers can you confirm that your driver version matches your CUDA runtime version?

**Comment by kevinch-nv** [comment]
Closing due to inactivity - looks to be a setup issue.

**Comment by vss96** [comment]
@kevinch-nv I have the proper drivers but I still get the same error, what should I do? 
Driver version: 440.33
Cuda: 10.2
Onnx: 1.6.0

**Comment by kevinch-nv** [comment]
@vss96 do you mind opening a new issue with the repro information of your machine?

**Comment by ynma-hanvo** [comment]
the same error , any updates ?, i have : 
Driver version: 440.33
Cuda: 10.2
Onnx: 1.6.0

**Comment by kevinch-nv** [comment]
What Python version and TRT version are you using?

**Comment by ynma-hanvo** [comment]
python 3.6 ,  using conda env. 
By the way, what is exactly this repo about, is it a onnx praser or not ?
i am confused as the tensorrt installation package already contains the onnx praser .

**Comment by yuanzhedong** [comment]
Get the same error, could anyone help? I'm using python 3.6 and trt 5.1
