### ISSUE TITLE
how to declare dynamic shape when transforming my onnx into tensorrt?

### ISSUE THREAD

**Issue by TengFeiHan0** [onnx/onnx-tensorrt#429]
I generated a onnx [model](https://drive.google.com/file/d/1wuKNpJqU7dUS3SLPiGa5kUQ1AY7APWXT/view?usp=sharing) under Pytorch1.3 

Then I'm going to transform my onnx model into an engine file that followed an official python sample(`yolo3v3_onnx`). I already knew that `dynamic shape` could be set by adding these codes 
```
import tensorrt
explicit_batch = 1 << (int)(tensorrt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
builder.create_network(explicit_batch)
```
However, I stilled failed when executing my code.

```
In node 788 (importInstanceNormalization): UNSUPPORTED_NODE: Assertion failed: !isDynamic(tensor_ptr->getDimensions()) && "InstanceNormalization does not support dynamic inputs!"
Traceback (most recent call last):
  File "samples/python/yolov3_onnx/onnx_to_tensorrt.py", line 187, in <module>
    main()
  File "samples/python/yolov3_onnx/onnx_to_tensorrt.py", line 158, in main
    with get_engine(onnx_file_path, engine_file_path) as engine, engine.create_execution_context() as context:
AttributeError: __exit__
```
I also provided some important parts of my code. You also could find my referred code under your TensorRT dir

```
def build_engine():
        """Takes an ONNX file and creates a TensorRT engine to run inference with"""
        explicit_batch = 1 << (int)(tensorrt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
        with trt.Builder(TRT_LOGGER) as builder, builder.create_network(explicit_batch)) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
            builder.max_workspace_size = 1 << 28 # 256MiB
            builder.max_batch_size = 1
            # Parse model file
            if not os.path.exists(onnx_file_path):
                print('ONNX file {} not found, please run yolov3_to_onnx.py first to generate it.'.format(onnx_file_path))
                exit(0)
            print('Loading ONNX file from path {}...'.format(onnx_file_path))
            with open(onnx_file_path, 'rb') as model:
                print('Beginning ONNX file parsing')
                if not parser.parse(model.read()):
                    print ('ERROR: Failed to parse the ONNX file.')
                    for error in range(parser.num_errors):
                        print (parser.get_error(error))
                    return None
            # The actual yolov3.onnx is generated with batch size 64. Reshape input to batch size 1
            network.get_input(0).shape = [1, 3, 608, 608]
            print('Completed parsing of ONNX file')
            print('Building an engine from file {}; this may take a while...'.format(onnx_file_path))
            engine = builder.build_cuda_engine(network)
            print("Completed creating Engine")
            with open(engine_file_path, "wb") as f:
                f.write(engine.serialize())
            return engine
```
any cues could be highly appreciated

**Comment by kevinch-nv** [comment]
Hi @TengFeiHan0, the InstanceNormalization plugin has been updated to support dynamic shapes in the latest TensorRT release. Can you try upgrading and importing your model again?

**Comment by kevinch-nv** [comment]
Closing due to no activity in this thread, if you are still having troubles feel free to open a new issue with a repro on the latest version of TRT.

**Comment by ThrillerWYY** [comment]
> Closing due to no activity in this thread, if you are still having troubles feel free to open a new issue with a repro on the latest version of TRT.

hello ,i have met the same problem,my vision is cuda10.0 torch1.4 tensorrt7.0 ,can you tell me how to solve ?
