### ISSUE TITLE
[8] Assertion failed: (nbSpatialDims == 2 && kernel_weights.shape.nbDims == 4) || (nbSpatialDims == 3 && kernel_weights.shape.nbDims == 5)

### ISSUE THREAD

**Issue by maulik2222** [onnx/onnx-tensorrt#451]
![onnx_trt_error](https://user-images.githubusercontent.com/42200806/80678492-9c6a4280-8ad8-11ea-94ab-0ac7d512eba7.png)
Hi,

My environment is tensorrt 6.0.1.10, onnx 1.6.0, python3.6.9, cuda10.0.

I tried to run onnx moddel on jetson nano and it raises the following error:
[TensorRT] ERROR: (Unnamed Layer* 0) [Scale]: at least 4 dimensions are required for input
Traceback (most recent call last):
  File "test_pt_onnx.py", line 19, in <module>
    engine = backend.prepare(model, device='CUDA:0')
  File "/usr/local/lib/python3.6/dist-packages/onnx_tensorrt-0.1.0-py3.6-linux-aarch64.egg/onnx_tensorrt/backend.py", line 200, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/onnx_tensorrt-0.1.0-py3.6-linux-aarch64.egg/onnx_tensorrt/backend.py", line 86, in __init__
    raise RuntimeError(msg)
RuntimeError: While parsing node number 1:
builtin_op_importers.cpp:788 In function importConv:
[8] Assertion failed: (nbSpatialDims == 2 && kernel_weights.shape.nbDims == 4) || (nbSpatialDims == 3 && kernel_weights.shape.nbDims == 5)
![error_trt](https://user-images.githubusercontent.com/42200806/80676909-68d9e900-8ad5-11ea-82d1-55892a624e74.png)

**Comment by ledinhtri97** [comment]
+1

**Comment by ShaneYS** [comment]
same error, anyone solved?

**Comment by kevinch-nv** [comment]
@maulik2222 can you try importing your model with the latest version of TensorRT (7.2)? If it doesn't work, can you attach the model here for internal investigation?

**Comment by kevinch-nv** [comment]
Closing due to no activity in this thread, if you are still having troubles feel free to open a new issue with a repro on the latest version of TRT.

**Comment by leaf918** [comment]
> @maulik2222 can you try importing your model with the latest version of TensorRT (7.2)? If it doesn't work, can you attach the model here for internal investigation?

Converting with tensorRT 7.2.2.3 ,occur same error:
`[03/29/2021-12:31:30] [E] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:706: --- End node ---
[03/29/2021-12:31:30] [E] [TRT] /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/ModelImporter.cpp:708: ERROR: /home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/builtin_op_importers.cpp:548 In function importConv:
[8] Assertion failed: nbSpatialDims == kernelWeights.shape.nbDims - 2
[03/29/2021-12:31:30] [E] Failed to parse onnx file
[03/29/2021-12:31:30] [E] Parsing model failed
[03/29/2021-12:31:30] [E] Engine creation failed
[03/29/2021-12:31:30] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # trtexec --onnx=lprnet_pytorch.onnx --saveEngine=lprnet_pytorch.trt --explicitBatch --workspace=4096`

**Comment by 004307ec** [comment]
It might be a failed shape inference for intermediate tensors.  Inserting Reshape node with constant valued tensor as shape before the Conv node might help.  You can use python onnx package to edit your onnx file.
