### ISSUE TITLE
Assertion failed: convertOnnxDims(onnxDtype.shape().dim(), trt_dims) Onnx-tensorrt model Conversion

### ISSUE THREAD

**Issue by jagadeesh-r1** [onnx/onnx-tensorrt#486]
I'm trying to convert an onnx model to tensorrt engine.The onnx model is obtained from a xgboost reggressor model.
I followed these steps:
import onnx
import onnx_tensorrt.backend as backend

model = onnx.load("/path/to/model.onnx")
engine = backend.prepare(model, device='CUDA:0')

The error stack :
'''
>>> engine = backend.prepare(model, device='CUDA:0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/onnx_tensorrt-0.1.0-py3.6-linux-x86_64.egg/onnx_tensorrt/backend.py", line 200, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/onnx_tensorrt-0.1.0-py3.6-linux-x86_64.egg/onnx_tensorrt/backend.py", line 86, in __init__
    raise RuntimeError(msg)
RuntimeError: While parsing node number -1:
input:191 In function importInput:
[7] Assertion failed: convertOnnxDims(onnxDtype.shape().dim(), trt_dims)
'''
What wrong with this code?

**Comment by kevinch-nv** [comment]
What version of TRT is this? We have recently made some changes to the master branch version of TRT (7.2) that should hopefully fix this issue.

You can also try importing your model through our CLI tool [trtexec](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec) that may give a more verbose error trace.

**Comment by kevinch-nv** [comment]
Closing due to no activity in this thread, if you are still having troubles feel free to open a new issue with a repro on the latest version of TRT.
