### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Xuner1213** [onnx/onnx-tensorrt#507]
how to solve this problem?
>>> import onnx_tensorrt.backend as backend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/soft/onnx-tensorrt-5.0/onnx_tensorrt/__init__.py", line 23, in <module>
    from . import backend
  File "/soft/onnx-tensorrt-5.0/onnx_tensorrt/backend.py", line 22, in <module>
    from .tensorrt_engine import Engine
  File "/soft/onnx-tensorrt-5.0/onnx_tensorrt/tensorrt_engine.py", line 23, in <module>
    import pycuda.gpuarray
  File "/root/anaconda3/envs/yolov4/lib/python3.5/site-packages/pycuda/gpuarray.py", line 4, in <module>
    import pycuda.elementwise as elementwise
  File "/root/anaconda3/envs/yolov4/lib/python3.5/site-packages/pycuda/elementwise.py", line 38, in <module>
    from pytools import memoize_method
  File "/root/anaconda3/envs/yolov4/lib/python3.5/site-packages/pytools/__init__.py", line 249
    __slots__: List[str] = []
             ^
SyntaxError: invalid syntax
>>>

**Comment by lijie2160** [comment]
I have same issue with you. Have you resolved it?

**Comment by lijie2160** [comment]
use   pip install pytools=='2019.1.1'  
you can solve it!

**Comment by Xuner1213** [comment]
> use pip install pytools=='2019.1.1'
> you can solve it!

Good

**Comment by Xuner1213** [comment]
> use pip install pytools=='2019.1.1'
> you can solve it!

Good

**Comment by kevinch-nv** [comment]
Closing this issue as it seems fixed.
