### ISSUE TITLE
Python wrapper import error

### ISSUE THREAD

**Issue by wangzilu** [onnx/onnx-tensorrt#58]
`>>> import onnx_tensorrt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "onnx_tensorrt/__init__.py", line 23, in <module>
    from . import backend
  File "onnx_tensorrt/backend.py", line 22, in <module>
    from . import parser
  File "onnx_tensorrt/parser/__init__.py", line 23, in <module>
    from ._nv_onnx_parser_bindings import *
ImportError: No module named _nv_onnx_parser_bindings
>>> 

`
tensorrt 4.0.1.6 python 2.7 cuda 9.0 cudnn 7.1.3 ubuntu 16.04

**Comment by benbarsdell** [comment]
Are you running the command from the onnx-tensorrt source directory? If so, it will incorrectly pick up the submodule from the onnx_tensorrt subdirectory instead of the installed version.

**Comment by wangzilu** [comment]
thank you very much! this helpful! @benbarsdell
