### ISSUE TITLE
TypeError: must be str, not bytes

### ISSUE THREAD

**Issue by vss96** [onnx/onnx-tensorrt#602]
Hi, I'm trying to use onnx tensorrt backend to run my onnx model. But when I run the script I get this particular error:
```
Traceback (most recent call last):
  File "onnxtrt.py", line 109, in <module>
    main()
  File "onnxtrt.py", line 101, in main
    engine = backend.prepare(model, device='CUDA:1')
  File "/home/ubuntu/wink-detectron/wink/lib/python3.6/site-packages/onnx_tensorrt-7.2.1.6.0-py3.6.egg/onnx_tensorrt/backend.py", line 254, in prepare
  File "/home/ubuntu/wink-detectron/wink/lib/python3.6/site-packages/onnx_tensorrt-7.2.1.6.0-py3.6.egg/onnx_tensorrt/backend.py", line 65, in __init__
  File "/home/ubuntu/wink-detectron/wink/lib/python3.6/site-packages/onnx_tensorrt-7.2.1.6.0-py3.6.egg/onnx_tensorrt/backend.py", line 162, in _set_device
  File "/home/ubuntu/wink-detectron/wink/lib/python3.6/site-packages/onnx_tensorrt-7.2.1.6.0-py3.6.egg/onnx_tensorrt/backend.py", line 40, in cudaSetDevice
TypeError: must be str, not bytes
```
Driver version: 440.33
Cuda version: 10.2
Onnx version: 1.8.0
Tensorrt version: 7.2.1.6

**Comment by vss96** [comment]
Error got resolved after shifting device from 1 to 0.
