### ISSUE TITLE
ONNX to TensorRT, used torch.topk ERROR

### ISSUE THREAD

**Issue by DonggeunYu** [onnx/onnx-tensorrt#606]
I used torch.topk().
But I get an error.

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

onnx: 1.6.0
onnx-tensorrt: 7.2.1.6.0

~~~
class TheModelClass(nn.Module):
    def __init__(self):
        super(TheModelClass, self).__init__()

    def forward(self, x):
        x = torch.topk(x, 2, dim=0)
        return x

the_model_class = TheModelClass()
the_model_class.to("cuda")
call = torch.tensor([1., 2., 3., 4. ,5.], device="cuda")
torch.onnx.export(the_model_class,
                      call,
                      "test.onnx",
                      export_params=True,
                      verbose=True,
                      opset_version=11,
                      do_constant_folding=False)

model = onnx.load("test.onnx")
call = np.array([1., 2., 3., 4., 5.])
engine = backend.prepare(model, device='CUDA')
output_data = engine.run(call)
print(output_data)
~~~

ERROR:
~~~
graph(%0 : Float(5:1, requires_grad=0, device=cuda:0)):
  %1 : Long(requires_grad=0, device=cpu) = onnx::Constant[value={2}]()
  %2 : Tensor = onnx::Constant[value={1}]()
  %3 : Tensor = onnx::Reshape(%1, %2)
  %4 : Float(2:1, requires_grad=0, device=cuda:0), %5 : Long(2:1, requires_grad=0, device=cuda:0) = onnx::TopK[axis=0, largest=1, sorted=1](%0, %3) # test.py:29:0
  return (%4, %5)

[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Traceback (most recent call last):
  File "test.py", line 49, in <module>
    engine = backend.prepare(model, device='CUDA')
  File "/usr/local/lib/python3.6/dist-packages/onnx_tensorrt-7.2.1.6.0-py3.6.egg/onnx_tensorrt/backend.py", line 254, in prepare
  File "/usr/local/lib/python3.6/dist-packages/onnx_tensorrt-7.2.1.6.0-py3.6.egg/onnx_tensorrt/backend.py", line 92, in __init__
RuntimeError: While parsing node number -1:
builtin_op_importers.cpp:3345 In function importTopK:
[8] Assertion failed: inputs.at(1).is_weights()
~~~

**Comment by xd-HKPC** [comment]
I met the same error. Could you tell me how to solve it?

**Comment by JeremySun1224** [comment]
Please, can the guys at NVIDIA tell us how to fix this, there are too many of these issues.
