### ISSUE TITLE
Package can't be installed without cuda runtime libraries available

### ISSUE THREAD

**Issue by DenisKuplyakov** [onnx/onnx-tensorrt#643]
By the moment setup.py script imports onxx_runtime [only to extract version information](https://github.com/onnx/onnx-tensorrt/blob/master/setup.py#L38). But this import leads to import of tensorrt, which requires cuda runtime libraries to be available. Thus makes it problematic to build docker images with onxx_runtime inside in CI/CD env without GPUs and cuda runtime.

Some refactoring is required to extract version from package without import of tensorrt, so build in CI/CD without GPU will be possible.

Log when tensorrt is not available on any command requiring setup.py (even not installing)
```
      ERROR: Command errored out with exit status 1:
       command: /home/dener/.pyenv/versions/eris-ct-worker/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/dener/.pyenv/versions/eris-ct-worker/src/onnx-tensorrt/setup.py'"'"'; __file__='"'"'/home/dener/.pyenv/versions/eris-ct-worker/src/onnx-tensorrt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ywrl82zv                                                                      
           cwd: /home/dener/.pyenv/versions/eris-ct-worker/src/onnx-tensorrt/                                                                                                                  
      Complete output (11 lines):                                                                                                                                                              
      Traceback (most recent call last):                                                                                                                                                       
        File "<string>", line 1, in <module>                                                                                                                                                   
        File "/home/dener/.pyenv/versions/eris-ct-worker/src/onnx-tensorrt/setup.py", line 18, in <module>                                                                                     
          import onnx_tensorrt                                                                                                                                                                 
        File "/home/dener/.pyenv/versions/3.8.5/envs/eris-ct-worker/src/onnx-tensorrt/onnx_tensorrt/__init__.py", line 23, in <module>                                                         
          from . import backend                                                                                                                                                                
        File "/home/dener/.pyenv/versions/3.8.5/envs/eris-ct-worker/src/onnx-tensorrt/onnx_tensorrt/backend.py", line 22, in <module>                                                          
          from .tensorrt_engine import Engine                                                                                                                                                  
        File "/home/dener/.pyenv/versions/3.8.5/envs/eris-ct-worker/src/onnx-tensorrt/onnx_tensorrt/tensorrt_engine.py", line 21, in <module>                                                  
          import tensorrt as trt                                                                                                                                                               
      ModuleNotFoundError: No module named 'tensorrt'  
```

Log on the situation when there is no cuda runtime available:
```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rxt1j24m/onnx-tensorrt_12e18d44d1d04b1a975d60ce9c274f9c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rxt1j24m/onnx-tensorrt_12e18d44d1d04b1a975d60ce9c274f9c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-crge83fu
         cwd: /tmp/pip-install-rxt1j24m/onnx-tensorrt_12e18d44d1d04b1a975d60ce9c274f9c/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rxt1j24m/onnx-tensorrt_12e18d44d1d04b1a975d60ce9c274f9c/setup.py", line 18, in <module>
        import onnx_tensorrt
      File "/tmp/pip-install-rxt1j24m/onnx-tensorrt_12e18d44d1d04b1a975d60ce9c274f9c/onnx_tensorrt/__init__.py", line 23, in <module>
        from . import backend
      File "/tmp/pip-install-rxt1j24m/onnx-tensorrt_12e18d44d1d04b1a975d60ce9c274f9c/onnx_tensorrt/backend.py", line 22, in <module>
        from .tensorrt_engine import Engine
      File "/tmp/pip-install-rxt1j24m/onnx-tensorrt_12e18d44d1d04b1a975d60ce9c274f9c/onnx_tensorrt/tensorrt_engine.py", line 22, in <module>
        import pycuda.driver
      File "/usr/local/lib/python3.8/dist-packages/pycuda/driver.py", line 62, in <module>
        from pycuda._driver import *  # noqa
    ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
    ----------------------------------------
```

**Comment by DenisKuplyakov** [comment]
Related issue from SO: https://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package

**Comment by kevinch-nv** [comment]
What version of ONNX-TRT are you using? Is this reproducible on master?

**Comment by DenisKuplyakov** [comment]
I were using 21.02 tag when created the issue. 

I haven't tried, but I'm sure it is still reproducible on master, as I see that the issue persists in code.

Let me describe step-by-step what happens for more clarity:
1. You invoke `python3 setup.py install` to setup package. Moreover here you can invoke any setup.py command (get version, dependencies list, etc.)
2. python evaluates `setup.py` script
3. `setup.py` imports onnx_tensorrt package [here](https://github.com/onnx/onnx-tensorrt/blob/master/setup.py#L5) *just to get its version* [here](https://github.com/onnx/onnx-tensorrt/blob/master/setup.py#L25)
4. python processes `onnx_tensorrt/__init__.py` and imports onxx_tensorrt/backend.py [here](https://github.com/onnx/onnx-tensorrt/blob/master/onnx_tensorrt/__init__.py#L5)
5. python processes `onxx_tensorrt/backend.py` and imports tensorrt [here](https://github.com/onnx/onnx-tensorrt/blob/master/onnx_tensorrt/backend.py#L5)
6. tensorrt requires cuda runtime to be imported

So this prevents you on installing package without tensorrt and cuda runtime available. That means you can't build docker image in CI on machine without GPU for further use on machines with GPU. Also you can't do dependency management or use any setup.py features without trt and cuda runtime.

By the moment I have ugly hacks in my Dockerfiles to solve the problem:
```docker
        git clone --depth 1 --branch 21.02 \
            https://github.com/onnx/onnx-tensorrt.git && \
        cd onnx-tensorrt && \
        cp -r onnx_tensorrt /usr/local/lib/python3.8/dist-packages && \
        cd .. && \
        rm -rf onnx-tensorrt; \
```

To solve the issue, as I said above, refactoring is required to extract version from package without import of tensorrt. [Here](https://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package) is more info on how to handle python package versioning correctly.

**Comment by drakenaver** [comment]
It happens to me, as well.

**Comment by nimdrak** [comment]
Hi @kevinch-nv @DenisKuplyakov — may I take this issue?
I can reproduce it on the latest release. Details below.

## Reproducibility

### Environment

* **Host**

  * CUDA: 12.9
  * NVIDIA driver: 575.57.08
* **Dockerfile I used**

  * Base: [https://github.com/NVIDIA/TensorRT/blob/v10.13.0/docker/ubuntu-22.04.Dockerfile](https://github.com/NVIDIA/TensorRT/blob/v10.13.0/docker/ubuntu-22.04.Dockerfile)
  * My changes for installing onnx-tensorrt: [https://github.com/nimdrak/build\_onnx\_tensorrt/commit/8715ed044839085c7bb9949c3bf24a6e6568c694](https://github.com/nimdrak/build_onnx_tensorrt/commit/8715ed044839085c7bb9949c3bf24a6e6568c694)
  * Full Dockerfile: [https://github.com/nimdrak/build\_onnx\_tensorrt/blob/main/Dockerfile](https://github.com/nimdrak/build_onnx_tensorrt/blob/main/Dockerfile)

### How I tested (switching container runtime)

#### 1) Runtime: **runc**

* `daemon.json`: [https://github.com/nimdrak/build\_onnx\_tensorrt/blob/main/daemon\_with\_runc\_runtime.json](https://github.com/nimdrak/build_onnx_tensorrt/blob/main/daemon_with_runc_runtime.json)
* Build: `docker build --tag test_10_13_without_gpu:0.1 .`
* **Result:** Fails (no GPU access during `docker build`), leading to `pycuda` import error:

```
-- Installing: /usr/local/lib/libnvonnxparser_static.a
Traceback (most recent call last):
  File "/onnx-tensorrt/setup.py", line 5, in <module>
    import onnx_tensorrt
  File "/onnx-tensorrt/onnx_tensorrt/__init__.py", line 5, in <module>
    from . import backend
  File "/onnx-tensorrt/onnx_tensorrt/backend.py", line 4, in <module>
    from .tensorrt_engine import Engine
  File "/onnx-tensorrt/onnx_tensorrt/tensorrt_engine.py", line 4, in <module>
    import pycuda.driver
  File "/usr/local/lib/python3.10/dist-packages/pycuda/driver.py", line 66, in <module>
    from pycuda._driver import *  # noqa
ImportError: /lib/x86_64-linux-gnu/libcuda.so.1: file too short
The command '/bin/bash -c git clone -b release/10.13-GA --single-branch --recurse-submodules https://github.com/onnx/onnx-tensorrt.git &&     cd onnx-tensorrt &&     mkdir build &&     cd build &&     cmake -DGPU_ARCHS="37 52 60 61 70 75" .. -DTENSORRT_ROOT=/TensorRT-10.13.0.35/include/ &&     make -j &&     make install &&     cd .. &&     python setup.py build &&     python -m pip install . &&     rm -rf build' returned a non-zero code: 1
```

#### 2) Runtime: **nvidia**

* `daemon.json`: [https://github.com/nimdrak/build\_onnx\_tensorrt/blob/main/daemon\_with\_nvidia\_runtime.json](https://github.com/nimdrak/build_onnx_tensorrt/blob/main/daemon_with_nvidia_runtime.json)
* Build: `docker build --tag test_10_13_with_gpu:0.1 .`
* **Result:** Succeeds (the NVIDIA runtime exposes GPU libraries at build time).

## Impact of fixing

* Removes the requirement to have an NVIDIA-enabled builder when building images that include `onnx-tensorrt`.
* Enables building in standard CI/CD environments **without** GPU access → better portability and productivity.

## Proposed approach

As @DenisKuplyakov suggested, refactor to avoid touching GPU-dependent code paths during build/install:

* Defer imports such as `pycuda.driver` and any direct CUDA access until runtime (lazy import / function-local import).
* Ensure `setup.py` / package import for build steps do not require a live CUDA driver.

If this plan sounds good, I’m happy to proceed and open a PR. Thanks!

**Comment by DenisKuplyakov** [comment]
> Hi [@kevinch-nv](https://github.com/kevinch-nv) [@DenisKuplyakov](https://github.com/DenisKuplyakov) — may I take this issue?

Hello!

I'm not a maintainer of the repo. But I suggest that @kevinch-nv won't mind.

> I’m happy to proceed and open a PR

There was a [PR](https://github.com/onnx/onnx-tensorrt/pull/768) from @ruro, but it wasn't accepted for years...

**Comment by nimdrak** [comment]
Thank you for your response, @DenisKuplyakov.

Yes, I also noticed the previous PR.
I’ll go ahead and open a new PR, including a description and test results to demonstrate that it works properly.

**Comment by nimdrak** [comment]
Hi @kevinch-nv — I opened two PRs with different approaches to address this issue:

1. https://github.com/onnx/onnx-tensorrt/pull/1035 — reads the version directly from the source file (minimal change, no import).

2. https://github.com/onnx/onnx-tensorrt/pull/1036 — PEP 517/pyproject.toml workflow (standards-based; avoids importing GPU-dependent code at build time).


I recommend #1035. When you have a moment, please review and feel free to leave any feedback.
