### ISSUE TITLE
[8] No importer registered for op: OneHot

### ISSUE THREAD

**Issue by DC-Lin** [onnx/onnx-tensorrt#727]
## Environment

**TensorRT Version**: 7.0.0.11
**ONNX-TensorRT Version / Branch**:7.0
**GPU Type**: 1080ti
**Nvidia Driver Version**: 460.84
**CUDA Version**: 10.0
**CUDNN Version**: ignore
**Operating System + Version**: ubuntu 18.04
**Python Version (if applicable)**: ptyhon3.6
**TensorFlow + TF2ONNX Version (if applicable)**: tensorflow-gpu-1.14 + ?
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Steps To Reproduce

My Problem:
Traceback (most recent call last):
  File "/data/software/miniconda3/envs/python3.6_NLPcomputer/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/software/miniconda3/envs/python3.6_NLPcomputer/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/software/miniconda3/envs/python3.6_NLPcomputer/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/software/miniconda3/envs/python3.6_NLPcomputer/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/data/software/miniconda3/envs/python3.6_NLPcomputer/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/software/miniconda3/envs/python3.6_NLPcomputer/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/disk005/NLP/unilever_claim_project/claim_cls/models/Categroy_deploy_unilever_V1.0.py", line 195, in predict
    resultclasses, resultprobability = parser.predict(_input_list)
  File "/disk005/NLP/unilever_claim_project/claim_cls/models/Categroy_deploy_unilever_V1.0.py", line 118, in predict
    engine = backend.prepare(model,device='CUDA:0')
  File "/disk005/NLP/unilever_claim_project/claim_cls/onnx_tensorrt/backend.py", line 200, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/disk005/NLP/unilever_claim_project/claim_cls/onnx_tensorrt/backend.py", line 86, in __init__
    raise RuntimeError(msg)
RuntimeError: While parsing node number 22:
ModelImporter.cpp:134 In function parseGraph:
[8] No importer registered for op: OneHot

**Comment by DC-Lin** [comment]
@tdp2110 @shinh @lutzroeder @Yangqing

**Comment by jdcmj** [comment]
I meet the same problem,have you solved the problem?

**Comment by Henry-Avery** [comment]
You guys look here https://github.com/onnx/onnx-tensorrt/blob
TensorRT 7.0 did not support op_type "OneHot"
