### ISSUE TITLE
return non-zero exit status 1

### ISSUE THREAD

**Issue by roachsinai** [onnx/onnx-tensorrt#749]
## Description

When build onnxruntime tensorrt ep from local (git clone microsoft/onnxruntime to local), get below error:

```
-- Generating done
-- Build files have been written to: D:/Libs/onnxruntime-tensorrt/build/Windows/Release
2021-09-23 22:29:09,768 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-09-23 22:29:09,768 build [INFO] - Building targets for Release configuration
2021-09-23 22:29:09,769 util.run [INFO] - Running subprocess in 'D:\Libs\onnxruntime-tensorrt'
['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'D:\\Libs\\onnxruntime-tensorrt\\\\build\\Windows\\Release', '--config', 'Release', '--', '/maxcpucount:16', '/nodeReuse:False']
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.0+0538acc04
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking File Globs
  "Checking python scripts for PEP8 conformance using flake8"
  custom_op_library.vcxproj -> D:\Libs\onnxruntime-tensorrt\build\Windows\Release\Release\custom_op_library.dll
  flatbuffers.vcxproj -> D:\Libs\onnxruntime-tensorrt\build\Windows\Release\external\flatbuffers\Release\flatbuffers.li
  b
  libprotobuf.vcxproj -> D:\Libs\onnxruntime-tensorrt\build\Windows\Release\external\protobuf\cmake\Release\libprotobuf
  .lib
  onnxruntime_providers_shared.vcxproj -> D:\Libs\onnxruntime-tensorrt\build\Windows\Release\Release\onnxruntime_provid
  ers_shared.dll
  test_execution_provider.vcxproj -> D:\Libs\onnxruntime-tensorrt\build\Windows\Release\Release\test_execution_provider
  .dll
  libprotoc.vcxproj -> D:\Libs\onnxruntime-tensorrt\build\Windows\Release\external\protobuf\cmake\Release\libprotoc.lib
  protoc.vcxproj -> D:\Libs\onnxruntime-tensorrt\build\Windows\Release\external\protobuf\cmake\Release\protoc.exe
  onnx_proto.vcxproj -> D:\Libs\onnxruntime-tensorrt\build\Windows\Release\external\onnx\Release\onnx_proto.lib
  onnx2trt_utils.cpp
  ShapeTensor.cpp
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include\NvInfer.h(2717,1): warning C4819: 该文件包含不能在当前 代码页(936)中表
示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 (编译源文件 D:\Libs\onnxruntime-tensorrt\cmake\external\onnx-tensorrt\onnx2trt_utils.cpp) [D
:\Libs\onnxruntime-tensorrt\build\Windows\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj]
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include\NvInfer.h(2717,1): warning C4819: 该文件包含不能在当前 代码页(936)中表
示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 (编译源文件 D:\Libs\onnxruntime-tensorrt\cmake\external\onnx-tensorrt\ShapeTensor.cpp) [D:\L
ibs\onnxruntime-tensorrt\build\Windows\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj]
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include\NvInfer.h(4513,1): warning C4819: 该文件包含不能在当前 代码页(936)中表
示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 (编译源文件 D:\Libs\onnxruntime-tensorrt\cmake\external\onnx-tensorrt\onnx2trt_utils.cpp) [D
:\Libs\onnxruntime-tensorrt\build\Windows\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj]
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include\NvInfer.h(4513,1): warning C4819: 该文件包含不能在当前 代码页(936)中表
示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 (编译源文件 D:\Libs\onnxruntime-tensorrt\cmake\external\onnx-tensorrt\ShapeTensor.cpp) [D:\L
ibs\onnxruntime-tensorrt\build\Windows\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj]
D:\Libs\onnxruntime-tensorrt\cmake\external\onnx-tensorrt\ShapeTensor.cpp(163,57): error C2078: 初始值设定项太多 [D:\Libs\onnxr
untime-tensorrt\build\Windows\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj]
D:\Libs\onnxruntime-tensorrt\cmake\external\onnx-tensorrt\ShapeTensor.cpp(389,30): error C2078: 初始值设定项太多 [D:\Libs\onnxr
untime-tensorrt\build\Windows\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj]
D:\Libs\onnxruntime-tensorrt\cmake\external\onnx-tensorrt\onnx2trt_utils.cpp(1594,35): error C2838: “kRNN”: 成员声明中的限定名称非
法 [D:\Libs\onnxruntime-tensorrt\build\Windows\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj]
D:\Libs\onnxruntime-tensorrt\cmake\external\onnx-tensorrt\onnx2trt_utils.cpp(1594,39): error C2065: “kRNN”: 未声明的标识符 [D:
\Libs\onnxruntime-tensorrt\build\Windows\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj]
D:\Libs\onnxruntime-tensorrt\cmake\external\onnx-tensorrt\onnx2trt_utils.cpp(1594,1): error C2051: case 表达式不是常量 [D:\Lib
s\onnxruntime-tensorrt\build\Windows\Release\external\onnx-tensorrt\nvonnxparser_static.vcxproj]
  onnxruntime_providers_cuda.vcxproj -> D:\Libs\onnxruntime-tensorrt\build\Windows\Release\Release\onnxruntime_provider
  s_cuda.dll
Traceback (most recent call last):
  File "D:\Libs\onnxruntime-tensorrt\\tools\ci_build\build.py", line 2162, in <module>
    sys.exit(main())
  File "D:\Libs\onnxruntime-tensorrt\\tools\ci_build\build.py", line 2086, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "D:\Libs\onnxruntime-tensorrt\\tools\ci_build\build.py", line 1064, in build_targets
    run_subprocess(cmd_args, env=env)
  File "D:\Libs\onnxruntime-tensorrt\\tools\ci_build\build.py", line 579, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "D:\Libs\onnxruntime-tensorrt\tools\python\util\run.py", line 44, in run
    env=env, shell=shell)
  File "C:\Users\benbenbj\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'D:\\Libs\\onnxruntime-tensorrt\\\\build\\Windows\\Release', '--config', 'Release', '--', '/maxcpucount:16', '/nodeReuse:False']' returned non-zero exit status 1.
```

## Environment

**TensorRT Version**: 8.0.3.4
**ONNX-TensorRT Version / Branch**: 99296a4
**GPU Type**: Nvidia
**Nvidia Driver Version**: 465.89
**CUDA Version**: 11.1
**CUDNN Version**: 8.2.1
**Operating System + Version**: Windows 10.0.19043.0
**Python Version (if applicable)**: 
**TensorFlow + TF2ONNX Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

onnxruntime version: 1.8.2

cudnn and tensorrt unzip files copied to "$env:CUDA_PATH".

## Steps To Reproduce

```
git clone https://github.com/microsoft/onnxruntime.git onnxruntime-tensorrt
.\build.bat --config Release --cmake_generator "Visual Studio 16 2019" --cudnn_home "$env:CUDA_PATH" --cuda_home "$env:CUDA_PATH" --use_tensorrt --tensorrt_home "$env:CUDA_PATH" --cuda_version 11.1 --build_shared_lib --parallel --skip_tests
```

## screenshots

![image](https://user-images.githubusercontent.com/9500049/134530971-ee4dd80d-9d73-4ce2-a69b-7631c34c9cae.png)

Thanks in advance!

**Comment by roachsinai** [comment]
Closed as should checkout release/8.0, thanks!
