### ISSUE TITLE
 Error Code 4: Internal Error (Network must have at least one output)

### ISSUE THREAD

**Issue by Tian14267** [onnx/onnx-tensorrt#846]
## Description

I get this error when covert onnx to TRT :

```
Loading ONNX file from path /data/vocoder_24k_3.onnx...
Beginning ONNX file parsing
[05/19/2022-19:11:54] [TRT] [W] onnx2trt_utils.cpp:365: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Completed parsing of ONNX file
Building an engine from file /data/vocoder_24k_3.onnx; this may take a while...
[05/19/2022-19:11:54] [TRT] [E] 4: [network.cpp::validate::2726] Error Code 4: Internal Error (Network must have at least one output)
Completed creating Engine
Traceback (most recent call last):
  File "onnx2trt_torch.py", line 111, in <module>
    engine = ONNX_build_engine(onnx_file_path,trt_model_out, write_engine)
  File "onnx2trt_torch.py", line 54, in ONNX_build_engine
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'
```
My onnx model is here (unzip it )
[vocoder_24k_3.zip](https://github.com/onnx/onnx-tensorrt/files/8728569/vocoder_24k_3.zip)

Does someone know how to solve this problem?

## Environment

**TensorRT Version**:  8.4.0.6
**ONNX-TensorRT Version / Branch**: 
**GPU Type**: 
**Nvidia Driver Version**:  
**CUDA Version**: 11.2
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**:  python 3.6
**TensorFlow + TF2ONNX Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by jackwish** [comment]
@Tian14267 Thank you for reporting this issue!

I looked into your model, the problem is that the shapes of the two branch graphs of `If_501` node are different, see as below. While TensorRT requires the shape to be the same currently: https://github.com/NVIDIA/TensorRT/blob/22.05/include/NvInfer.h#L5040

```py
if 809: 811 = squeeze(804) # shape [1,Squeeze811_dim_1]
else: 812 = identity(804) # shape [Identity812_dim_0,1,Squeeze811_dim_1]
```

It seems the last layers of your model can be merged as one Reshape. Could you try to modify the Torch code?

![reshape-subgraph](https://user-images.githubusercontent.com/4936589/169471137-e5f6d415-1e41-4d9f-8d46-6038da61bdc4.png)

**Comment by Tian14267** [comment]
> 



> @Tian14267 Thank you for reporting this issue!
> 
> I looked into your model, the problem is that the shapes of the two branch graphs of `If_501` node are different, see as below. While TensorRT requires the shape to be the same currently: https://github.com/NVIDIA/TensorRT/blob/22.05/include/NvInfer.h#L5040
> 
> ```python
> if 809: 811 = squeeze(804) # shape [1,Squeeze811_dim_1]
> else: 812 = identity(804) # shape [Identity812_dim_0,1,Squeeze811_dim_1]
> ```
> 
> It seems the last layers of your model can be merged as a Reshape+Transpose. Could you try to modify the Torch code?
> 
> ![reshape-subgraph](https://user-images.githubusercontent.com/4936589/169471137-e5f6d415-1e41-4d9f-8d46-6038da61bdc4.png)

Thank you very much. I will try to modify my torch code and try again.

**Comment by Tian14267** [comment]
> ```python
> 1,Squeeze811_dim_1
> ```

Excuse me , I try to modify torch code, but still get same error . I remove layer after last `Conv`, That error still appear.
I use python code to covert TRT, It still.
**My onnx model is here:** 
[vocoder_24k_4.zip](https://github.com/onnx/onnx-tensorrt/files/8747067/vocoder_24k_4.zip)
**My pytorch code is here:**
[https://github.com/kan-bayashi/ParallelWaveGAN](url)
**The pytorch model I use to covert onnx is here:**
<img width="726" alt="1" src="https://user-images.githubusercontent.com/27938135/169638514-dcae246b-ac5a-4942-bb76-c6ce2643f224.png">

**The python code I use to covert TRT is here:**
<img width="771" alt="2" src="https://user-images.githubusercontent.com/27938135/169638641-44d4d827-aae8-478e-a0fa-469534472620.png">

Can someone tell me how to solve It ?

**Comment by Tian14267** [comment]
@jackwish

**Comment by jackwish** [comment]
@Tian14267 What's the error you are getting in your new model?

I am getting
```
[05/23/2022-05:47:05] [E] [TRT] ModelImporter.cpp:773: While parsing node number 12 [RandomNormalLike -> "238"]:
[05/23/2022-05:47:05] [E] [TRT] ModelImporter.cpp:774: --- Begin node ---
[05/23/2022-05:47:05] [E] [TRT] ModelImporter.cpp:775: input: "237"
output: "238"
name: "RandomNormalLike_12"
op_type: "RandomNormalLike"
attribute {
  name: "dtype"
  i: 1
  type: INT
}

[05/23/2022-05:47:05] [E] [TRT] ModelImporter.cpp:776: --- End node ---
[05/23/2022-05:47:05] [E] [TRT] ModelImporter.cpp:779: ERROR: builtin_op_importers.cpp:4890 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
```

TensorRT currently doesn't support `RandomNormalLike`, but we are working on enabling more ONNX operators.

Please let me know if the error is the same as your side.

**Comment by Tian14267** [comment]
> 



> @Tian14267 What's the error you are getting in your new model?
> 
> I am getting
> 
> ```
> [05/23/2022-05:47:05] [E] [TRT] ModelImporter.cpp:773: While parsing node number 12 [RandomNormalLike -> "238"]:
> [05/23/2022-05:47:05] [E] [TRT] ModelImporter.cpp:774: --- Begin node ---
> [05/23/2022-05:47:05] [E] [TRT] ModelImporter.cpp:775: input: "237"
> output: "238"
> name: "RandomNormalLike_12"
> op_type: "RandomNormalLike"
> attribute {
>   name: "dtype"
>   i: 1
>   type: INT
> }
> 
> [05/23/2022-05:47:05] [E] [TRT] ModelImporter.cpp:776: --- End node ---
> [05/23/2022-05:47:05] [E] [TRT] ModelImporter.cpp:779: ERROR: builtin_op_importers.cpp:4890 In function importFallbackPluginImporter:
> [8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
> ```
> 
> TensorRT currently doesn't support `RandomNormalLike`, but we are working on enabling more ONNX operators.
> 
> Please let me know if the error is the same as your side.

**I get similar error with** `onnx2trt`

```
----------------------------------------------------------------
Input filename:   /data/fffan/1_DeepLearning_code/9_TTS/0_tools_onnx_trt/data/paddle_onnx/onnx_model/vocoder_24k_3.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    pytorch
Producer version: 1.8
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
[2022-05-25 05:48:22 WARNING] onnx2trt_utils.cpp:368: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
While parsing node number 12 [RandomNormalLike -> "238"]:
ERROR: builtin_op_importers.cpp:4788 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
```

**But when I use python code to covert , I don't get those error but**
`[05/19/2022-19:11:54] [TRT] [E] 4: [network.cpp::validate::2726] Error Code 4: Internal Error (Network must have at least one output)`

**Comment by Tian14267** [comment]
@jackwish

**Comment by jackwish** [comment]
Have you changed your python code to use the new ONNX model? `onnx2trt` is the parser in your code.

**Comment by jackwish** [comment]
For the `RandomNormalLike` issue, could you please create a new issue to track? (as this issue is about the model definition.
